// lib/players.ts

export const WORLD_CUP_PLAYERS = [
    // --- REP. CECA ---
    { country: 'Rep. Ceca', name: 'Coufal' }, { country: 'Rep. Ceca', name: 'Doudera' }, { country: 'Rep. Ceca', name: 'Holes' }, { country: 'Rep. Ceca', name: 'Hranac' }, { country: 'Rep. Ceca', name: 'Chaloupek' }, { country: 'Rep. Ceca', name: 'Jurasek' }, { country: 'Rep. Ceca', name: 'Krejci' }, { country: 'Rep. Ceca', name: 'Zeleny' }, { country: 'Rep. Ceca', name: 'Zima' }, { country: 'Rep. Ceca', name: 'Cerv' }, { country: 'Rep. Ceca', name: 'Darida' }, { country: 'Rep. Ceca', name: 'Provod' }, { country: 'Rep. Ceca', name: 'Sadilek' }, { country: 'Rep. Ceca', name: 'Sochurek' }, { country: 'Rep. Ceca', name: 'Sojka' }, { country: 'Rep. Ceca', name: 'Soucek' }, { country: 'Rep. Ceca', name: 'Sulc' }, { country: 'Rep. Ceca', name: 'Visinsky' }, { country: 'Rep. Ceca', name: 'Chory' }, { country: 'Rep. Ceca', name: 'Hlozek' }, { country: 'Rep. Ceca', name: 'Chytil' }, { country: 'Rep. Ceca', name: 'Kuchta' }, { country: 'Rep. Ceca', name: 'Schick' },
    // --- MESSICO ---
    { country: 'Messico', name: 'Reyes' }, { country: 'Messico', name: 'Gallardo' }, { country: 'Messico', name: 'Sanchez' }, { country: 'Messico', name: 'Montes' }, { country: 'Messico', name: 'Vasquez' }, { country: 'Messico', name: 'L. Chavez' }, { country: 'Messico', name: 'Lira' }, { country: 'Messico', name: 'Romo' }, { country: 'Messico', name: 'Vargas' }, { country: 'Messico', name: 'Gutierrez' }, { country: 'Messico', name: 'Pineda' }, { country: 'Messico', name: 'Alvarez' }, { country: 'Messico', name: 'Mora' }, { country: 'Messico', name: 'Huerta' }, { country: 'Messico', name: 'Fidalgo' }, { country: 'Messico', name: 'C. Chavez' }, { country: 'Messico', name: 'Alvarado' }, { country: 'Messico', name: 'Vega' }, { country: 'Messico', name: 'Quiñones' }, { country: 'Messico', name: 'Gimenez' }, { country: 'Messico', name: 'Martinez' }, { country: 'Messico', name: 'Gonzalez' }, { country: 'Messico', name: 'Jimenez' },
    // --- SUDAFRICA ---
    { country: 'Sudafrica', name: 'Modiba' }, { country: 'Sudafrica', name: 'Mudau' }, { country: 'Sudafrica', name: 'Sibisi' }, { country: 'Sudafrica', name: 'Mbokazi' }, { country: 'Sudafrica', name: 'Okon' }, { country: 'Sudafrica', name: 'Kabini' }, { country: 'Sudafrica', name: 'Ndamane' }, { country: 'Sudafrica', name: 'Matuludi' }, { country: 'Sudafrica', name: 'Cross' }, { country: 'Sudafrica', name: 'Makhanya' }, { country: 'Sudafrica', name: 'Mokoena' }, { country: 'Sudafrica', name: 'Sithole' }, { country: 'Sudafrica', name: 'Mbatha' }, { country: 'Sudafrica', name: 'Adams' }, { country: 'Sudafrica', name: 'Zwane' }, { country: 'Sudafrica', name: 'Foster' }, { country: 'Sudafrica', name: 'Makgopa' }, { country: 'Sudafrica', name: 'Appollis' }, { country: 'Sudafrica', name: 'Rayners' }, { country: 'Sudafrica', name: 'Mofokeng' }, { country: 'Sudafrica', name: 'Maseko' }, { country: 'Sudafrica', name: 'Moremi' }, { country: 'Sudafrica', name: 'Sebelebele' },
    // --- COREA SUD ---
    { country: 'Corea Sud', name: 'Kim Moon-hwan' }, { country: 'Corea Sud', name: 'Kim Min-jae' }, { country: 'Corea Sud', name: 'Kim Tae-hyeon' }, { country: 'Corea Sud', name: 'Park Jin-seob' }, { country: 'Corea Sud', name: 'Seol Young-woo' }, { country: 'Corea Sud', name: 'Jens Castrop' }, { country: 'Corea Sud', name: 'Lee Ki-hyuk' }, { country: 'Corea Sud', name: 'Lee Tae-seok' }, { country: 'Corea Sud', name: 'Lee Han-beom' }, { country: 'Corea Sud', name: 'Cho Yi-je' }, { country: 'Corea Sud', name: 'Kim Jin-gyu' }, { country: 'Corea Sud', name: 'Bae Jun-ho' }, { country: 'Corea Sud', name: 'Paik Seung-ho' }, { country: 'Corea Sud', name: 'Yang Hyun-jun' }, { country: 'Corea Sud', name: 'Eom Ji-sung' }, { country: 'Corea Sud', name: 'Lee Kang-in' }, { country: 'Corea Sud', name: 'Lee Dong-gyeong' }, { country: 'Corea Sud', name: 'Lee Jae-sung' }, { country: 'Corea Sud', name: 'Hwang In-beom' }, { country: 'Corea Sud', name: 'Hwang Hee-chan' }, { country: 'Corea Sud', name: 'Son Heung-min' }, { country: 'Corea Sud', name: 'Oh Hyeon-gyu' }, { country: 'Corea Sud', name: 'Cho Gue-sung' },
    // --- BOSNIA ---
    { country: 'Bosnia', name: 'Dedic' }, { country: 'Bosnia', name: 'Katic' }, { country: 'Bosnia', name: 'Radeljic' }, { country: 'Bosnia', name: 'Celik' }, { country: 'Bosnia', name: 'Mujakic' }, { country: 'Bosnia', name: 'Muharemovic' }, { country: 'Bosnia', name: 'Kolasinac' }, { country: 'Bosnia', name: 'Hadzikadunic' }, { country: 'Bosnia', name: 'Hadziahmetovic' }, { country: 'Bosnia', name: 'Sunjic' }, { country: 'Bosnia', name: 'Tahirovic' }, { country: 'Bosnia', name: 'Burnic' }, { country: 'Bosnia', name: 'Gigovic' }, { country: 'Bosnia', name: 'Mahmic' }, { country: 'Bosnia', name: 'Basic' }, { country: 'Bosnia', name: 'Memic' }, { country: 'Bosnia', name: 'Alajbegovic' }, { country: 'Bosnia', name: 'Bajraktarevic' }, { country: 'Bosnia', name: 'Bazdar' }, { country: 'Bosnia', name: 'Lukic' }, { country: 'Bosnia', name: 'Tabakovic' }, { country: 'Bosnia', name: 'Demirovic' }, { country: 'Bosnia', name: 'Dzeko' },
    // --- CANADA ---
    { country: 'Canada', name: 'Cornelius' }, { country: 'Canada', name: 'Laryea' }, { country: 'Canada', name: 'Sigur' }, { country: 'Canada', name: 'Waterman' }, { country: 'Canada', name: 'De Fougerolles' }, { country: 'Canada', name: 'Bombito' }, { country: 'Canada', name: 'Johnston' }, { country: 'Canada', name: 'Davies' }, { country: 'Canada', name: 'Jones' }, { country: 'Canada', name: 'Eustaquio' }, { country: 'Canada', name: 'Konè' }, { country: 'Canada', name: 'Buchanan' }, { country: 'Canada', name: 'Choiniere' }, { country: 'Canada', name: 'Ahmed' }, { country: 'Canada', name: 'Saliba' }, { country: 'Canada', name: 'Millar' }, { country: 'Canada', name: 'Flores' }, { country: 'Canada', name: 'Shaffelburg' }, { country: 'Canada', name: 'Osorio' }, { country: 'Canada', name: 'David' }, { country: 'Canada', name: 'Larin' }, { country: 'Canada', name: 'Oluwaseyi' },
    // --- QATAR ---
    { country: 'Qatar', name: 'Al-Alawi' }, { country: 'Qatar', name: 'Khoukhi' }, { country: 'Qatar', name: 'Elamin' }, { country: 'Qatar', name: 'Mendes' }, { country: 'Qatar', name: 'Laye' }, { country: 'Qatar', name: 'Pedro Miguel' }, { country: 'Qatar', name: 'Al-Hussain' }, { country: 'Qatar', name: 'Al-Brake' }, { country: 'Qatar', name: 'Madibo' }, { country: 'Qatar', name: 'Hatem' }, { country: 'Qatar', name: 'Fatehi' }, { country: 'Qatar', name: 'Boudiaf' }, { country: 'Qatar', name: 'Gaber' }, { country: 'Qatar', name: 'Al-Mannai' }, { country: 'Qatar', name: 'Al-Ganehi' }, { country: 'Qatar', name: 'Alaaeldin' }, { country: 'Qatar', name: 'Afif' }, { country: 'Qatar', name: 'A. Ali' }, { country: 'Qatar', name: 'Edmilson Junior' }, { country: 'Qatar', name: 'Al-Haydos' }, { country: 'Qatar', name: 'Muntari' }, { country: 'Qatar', name: 'Jamshid' }, { country: 'Qatar', name: 'Abdurisag' },
    // --- SVIZZERA ---
    { country: 'Svizzera', name: 'Ricardo Rodriguez' }, { country: 'Svizzera', name: 'Akanji' }, { country: 'Svizzera', name: 'Widmer' }, { country: 'Svizzera', name: 'Elvedi' }, { country: 'Svizzera', name: 'Muheim' }, { country: 'Svizzera', name: 'Amenda' }, { country: 'Svizzera', name: 'Comert' }, { country: 'Svizzera', name: 'Jaquez' }, { country: 'Svizzera', name: 'Aebischer' }, { country: 'Svizzera', name: 'Fassnacht' }, { country: 'Svizzera', name: 'Freuler' }, { country: 'Svizzera', name: 'Jashari' }, { country: 'Svizzera', name: 'Manzambi' }, { country: 'Svizzera', name: 'Rieder' }, { country: 'Svizzera', name: 'Sow' }, { country: 'Svizzera', name: 'Xhaka' }, { country: 'Svizzera', name: 'Zakaria' }, { country: 'Svizzera', name: 'Amdouni' }, { country: 'Svizzera', name: 'Embolo' }, { country: 'Svizzera', name: 'Itten' }, { country: 'Svizzera', name: 'Ndoye' }, { country: 'Svizzera', name: 'Okafor' }, { country: 'Svizzera', name: 'Vargas' },
    // --- BRASILE ---
    { country: 'Brasile', name: 'Alex Sandro' }, { country: 'Brasile', name: 'Bremer' }, { country: 'Brasile', name: 'Danilo' }, { country: 'Brasile', name: 'Douglas Santos' }, { country: 'Brasile', name: 'Gabriel' }, { country: 'Brasile', name: 'Ibanez' }, { country: 'Brasile', name: 'Leo Pereira' }, { country: 'Brasile', name: 'Marquinhos' }, { country: 'Brasile', name: 'Wesley' }, { country: 'Brasile', name: 'Bruno Guimaraes' }, { country: 'Brasile', name: 'Casemiro' }, { country: 'Brasile', name: 'Lucas Paquetá' }, { country: 'Brasile', name: 'Fabinho' }, { country: 'Brasile', name: 'Endrick' }, { country: 'Brasile', name: 'Martinelli' }, { country: 'Brasile', name: 'Igor Thiago' }, { country: 'Brasile', name: 'Luis Henrique' }, { country: 'Brasile', name: 'Matheus Cunha' }, { country: 'Brasile', name: 'Neymar' }, { country: 'Brasile', name: 'Rayan' }, { country: 'Brasile', name: 'Vinicius Jr' }, { country: 'Brasile', name: 'Raphinha' },
    // --- HAITI ---
    { country: 'Haiti', name: 'Arcus' }, { country: 'Haiti', name: 'Paugain' }, { country: 'Haiti', name: 'Lacroix' }, { country: 'Haiti', name: 'Experience' }, { country: 'Haiti', name: 'Duverne' }, { country: 'Haiti', name: 'Ade' }, { country: 'Haiti', name: 'Delcroix' }, { country: 'Haiti', name: 'Thermoncy' }, { country: 'Haiti', name: 'Sainté' }, { country: 'Haiti', name: 'L. Pierre' }, { country: 'Haiti', name: 'Danley' }, { country: 'Haiti', name: 'Bellegarde' }, { country: 'Haiti', name: 'W. Pierre' }, { country: 'Haiti', name: 'Simon' }, { country: 'Haiti', name: 'Deedson' }, { country: 'Haiti', name: 'Casimir' }, { country: 'Haiti', name: 'Etienne' }, { country: 'Haiti', name: 'Providence' }, { country: 'Haiti', name: 'Nazon' }, { country: 'Haiti', name: 'Pierrot' }, { country: 'Haiti', name: 'Isidor' }, { country: 'Haiti', name: 'Fortuné' }, { country: 'Haiti', name: 'Joseph' },
    // --- MAROCCO ---
    { country: 'Marocco', name: 'Mazraoui' }, { country: 'Marocco', name: 'Salah-Eddine' }, { country: 'Marocco', name: 'Belammari' }, { country: 'Marocco', name: 'Aguerd' }, { country: 'Marocco', name: 'Riad' }, { country: 'Marocco', name: 'Diop' }, { country: 'Marocco', name: 'Halhal' }, { country: 'Marocco', name: 'Hakimi' }, { country: 'Marocco', name: 'El Ouahdi' }, { country: 'Marocco', name: 'El Mourabet' }, { country: 'Marocco', name: 'Bouaddi' }, { country: 'Marocco', name: 'El Aynaoui' }, { country: 'Marocco', name: 'Amrabat' }, { country: 'Marocco', name: 'Ounahi' }, { country: 'Marocco', name: 'El Khannouss' }, { country: 'Marocco', name: 'Saibari' }, { country: 'Marocco', name: 'Elzazzouli' }, { country: 'Marocco', name: 'Talbi' }, { country: 'Marocco', name: 'Rahimi' }, { country: 'Marocco', name: 'El Kaabi' }, { country: 'Marocco', name: 'Brahim Diaz' }, { country: 'Marocco', name: 'Gessime' }, { country: 'Marocco', name: 'Amaimouni' },
    // --- SCOZIA ---
    { country: 'Scozia', name: 'Hanley' }, { country: 'Scozia', name: 'Hendry' }, { country: 'Scozia', name: 'Hickey' }, { country: 'Scozia', name: 'Hyam' }, { country: 'Scozia', name: 'McKenna' }, { country: 'Scozia', name: 'Patterson' }, { country: 'Scozia', name: 'Ralston' }, { country: 'Scozia', name: 'Robertson' }, { country: 'Scozia', name: 'Souttar' }, { country: 'Scozia', name: 'Tierney' }, { country: 'Scozia', name: 'Christie' }, { country: 'Scozia', name: 'Curtis' }, { country: 'Scozia', name: 'Ferguson' }, { country: 'Scozia', name: 'Gannon-Doak' }, { country: 'Scozia', name: 'McGinn' }, { country: 'Scozia', name: 'McLean' }, { country: 'Scozia', name: 'McTominay' }, { country: 'Scozia', name: 'Fletcher' }, { country: 'Scozia', name: 'Adams' }, { country: 'Scozia', name: 'Dykes' }, { country: 'Scozia', name: 'Hirst' }, { country: 'Scozia', name: 'Shankland' }, { country: 'Scozia', name: 'Stewart' },
    // --- AUSTRALIA ---
    { country: 'Australia', name: 'Behich' }, { country: 'Australia', name: 'Bos' }, { country: 'Australia', name: 'Burgess' }, { country: 'Australia', name: 'Circati' }, { country: 'Australia', name: 'Degenek' }, { country: 'Australia', name: 'Geria' }, { country: 'Australia', name: 'Herrington' }, { country: 'Australia', name: 'Italiano' }, { country: 'Australia', name: 'Souttar' }, { country: 'Australia', name: 'Trewin' }, { country: 'Australia', name: 'Devlin' }, { country: 'Australia', name: 'Hrustic' }, { country: 'Australia', name: 'Irvine' }, { country: 'Australia', name: 'Metcalfe' }, { country: 'Australia', name: 'Okon-Engstler' }, { country: 'Australia', name: 'O’Neill' }, { country: 'Australia', name: 'Irankunda' }, { country: 'Australia', name: 'Leckie' }, { country: 'Australia', name: 'Mabil' }, { country: 'Australia', name: 'Toure' }, { country: 'Australia', name: 'Velupillay' }, { country: 'Australia', name: 'Volpato' }, { country: 'Australia', name: 'Yengi' },
    // --- PARAGUAY ---
    { country: 'Paraguay', name: 'G. Velazquez' }, { country: 'Paraguay', name: 'Caceres' }, { country: 'Paraguay', name: 'Gustavo Gomez' }, { country: 'Paraguay', name: 'Alderete' }, { country: 'Paraguay', name: 'Balbuena' }, { country: 'Paraguay', name: 'Canale' }, { country: 'Paraguay', name: 'J. Alonso' }, { country: 'Paraguay', name: 'Maidana' }, { country: 'Paraguay', name: 'Diego Gomez' }, { country: 'Paraguay', name: 'Cubas' }, { country: 'Paraguay', name: 'Bobadilla' }, { country: 'Paraguay', name: 'Galarza' }, { country: 'Paraguay', name: 'Ojeda' }, { country: 'Paraguay', name: 'Magalhaes' }, { country: 'Paraguay', name: 'Gamarra' }, { country: 'Paraguay', name: 'Caballero' }, { country: 'Paraguay', name: 'Almiron' }, { country: 'Paraguay', name: 'Enciso' }, { country: 'Paraguay', name: 'Ramon Sosa' }, { country: 'Paraguay', name: 'Sanabria' }, { country: 'Paraguay', name: 'Alex Arce' }, { country: 'Paraguay', name: 'Avalos' }, { country: 'Paraguay', name: 'Pitta' },
    // --- TURCHIA ---
    { country: 'Turchia', name: 'Akaydin' }, { country: 'Turchia', name: 'Bardakci' }, { country: 'Turchia', name: 'Celik' }, { country: 'Turchia', name: 'Demiral' }, { country: 'Turchia', name: 'Elmall' }, { country: 'Turchia', name: 'Kabak' }, { country: 'Turchia', name: 'Kadioglu' }, { country: 'Turchia', name: 'Muldur' }, { country: 'Turchia', name: 'Soyuncu' }, { country: 'Turchia', name: 'Ayhan' }, { country: 'Turchia', name: 'Calhanoglu' }, { country: 'Turchia', name: 'Kokcu' }, { country: 'Turchia', name: 'Ozcan' }, { country: 'Turchia', name: 'Yuksek' }, { country: 'Turchia', name: 'Akgun' }, { country: 'Turchia', name: 'Akturkoglu' }, { country: 'Turchia', name: 'Aydin' }, { country: 'Turchia', name: 'Gul' }, { country: 'Turchia', name: 'Guler' }, { country: 'Turchia', name: 'Kahveci' }, { country: 'Turchia', name: 'Uzun' }, { country: 'Turchia', name: 'Yildiz' }, { country: 'Turchia', name: 'Yilmaz' },
    // --- USA ---
    { country: 'USA', name: 'Dest' }, { country: 'USA', name: 'Richards' }, { country: 'USA', name: 'Robinson' }, { country: 'USA', name: 'Trusty' }, { country: 'USA', name: 'Ream' }, { country: 'USA', name: 'Freeman' }, { country: 'USA', name: 'Arfsten' }, { country: 'USA', name: 'McKenzie' }, { country: 'USA', name: 'Scally' }, { country: 'USA', name: 'Adams' }, { country: 'USA', name: 'Reyna' }, { country: 'USA', name: 'McKennie' }, { country: 'USA', name: 'Pulisic' }, { country: 'USA', name: 'Aaronson' }, { country: 'USA', name: 'Berhalter' }, { country: 'USA', name: 'Roldan' }, { country: 'USA', name: 'Tillman' }, { country: 'USA', name: 'Weah' }, { country: 'USA', name: 'Zendejas' }, { country: 'USA', name: 'Pepi' }, { country: 'USA', name: 'Wright' }, { country: 'USA', name: 'Balogun' },
    // --- CURAÇAO ---
    { country: 'Curaçao', name: 'Bazoer' }, { country: 'Curaçao', name: 'Brenet' }, { country: 'Curaçao', name: 'Van Eijma' }, { country: 'Curaçao', name: 'Floranus' }, { country: 'Curaçao', name: 'Fonville' }, { country: 'Curaçao', name: 'Gaari' }, { country: 'Curaçao', name: 'Obispo' }, { country: 'Curaçao', name: 'Sambo' }, { country: 'Curaçao', name: 'Juninho Bacuna' }, { country: 'Curaçao', name: 'Leandro Bacuna' }, { country: 'Curaçao', name: 'Comenencia' }, { country: 'Curaçao', name: 'Felida' }, { country: 'Curaçao', name: 'Martha' }, { country: 'Curaçao', name: 'Noslin' }, { country: 'Curaçao', name: 'Roemeratoe' }, { country: 'Curaçao', name: 'Antonisse' }, { country: 'Curaçao', name: 'Chong' }, { country: 'Curaçao', name: 'Gorré' }, { country: 'Curaçao', name: 'Hansen' }, { country: 'Curaçao', name: 'Kastaneer' }, { country: 'Curaçao', name: 'Kuwas' }, { country: 'Curaçao', name: 'Locadia' }, { country: 'Curaçao', name: 'Margaritha' },
    // --- ECUADOR ---
    { country: 'Ecuador', name: 'Pacho' }, { country: 'Ecuador', name: 'Hincapiè' }, { country: 'Ecuador', name: 'Ordonez' }, { country: 'Ecuador', name: 'Estupinan' }, { country: 'Ecuador', name: 'Medina' }, { country: 'Ecuador', name: 'Preciado' }, { country: 'Ecuador', name: 'Porozo' }, { country: 'Ecuador', name: 'Torres' }, { country: 'Ecuador', name: 'M. Caicedo' }, { country: 'Ecuador', name: 'Paez' }, { country: 'Ecuador', name: 'Castillo' }, { country: 'Ecuador', name: 'Vite' }, { country: 'Ecuador', name: 'Franco' }, { country: 'Ecuador', name: 'Alcivar' }, { country: 'Ecuador', name: 'Yeboah' }, { country: 'Ecuador', name: 'Angulo' }, { country: 'Ecuador', name: 'Plata' }, { country: 'Ecuador', name: 'Rodriguez' }, { country: 'Ecuador', name: 'Arevalo' }, { country: 'Ecuador', name: 'Minda' }, { country: 'Ecuador', name: 'J. Caicedo' }, { country: 'Ecuador', name: 'A. Valencia' }, { country: 'Ecuador', name: 'E. Valencia' },
    // --- GERMANIA ---
    { country: 'Germania', name: 'Anton' }, { country: 'Germania', name: 'Brown' }, { country: 'Germania', name: 'Kimmich' }, { country: 'Germania', name: 'Raum' }, { country: 'Germania', name: 'Rudiger' }, { country: 'Germania', name: 'Thiaw' }, { country: 'Germania', name: 'Schlotterbeck' }, { country: 'Germania', name: 'Tah' }, { country: 'Germania', name: 'Goretzka' }, { country: 'Germania', name: 'Nmecha' }, { country: 'Germania', name: 'Stiller' }, { country: 'Germania', name: 'Leweling' }, { country: 'Germania', name: 'Karl' }, { country: 'Germania', name: 'Pavlovic' }, { country: 'Germania', name: 'Musiala' }, { country: 'Germania', name: 'Amiri' }, { country: 'Germania', name: 'Gross' }, { country: 'Germania', name: 'Havertz' }, { country: 'Germania', name: 'Sané' }, { country: 'Germania', name: 'Undav' }, { country: 'Germania', name: 'Beier' }, { country: 'Germania', name: 'Woltemade' }, { country: 'Germania', name: 'Wirtz' },
    // --- COSTA D'AVORIO ---
    { country: "Costa d'Avorio", name: 'Agbadou' }, { country: "Costa d'Avorio", name: 'Operi' }, { country: "Costa d'Avorio", name: 'O. Diomandé' }, { country: "Costa d'Avorio", name: 'Doué' }, { country: "Costa d'Avorio", name: 'Konan' }, { country: "Costa d'Avorio", name: 'Kossounou' }, { country: "Costa d'Avorio", name: 'Ndicka' }, { country: "Costa d'Avorio", name: 'Singo' }, { country: "Costa d'Avorio", name: 'Seko Fofana' }, { country: "Costa d'Avorio", name: 'Guiagon' }, { country: "Costa d'Avorio", name: 'Kessié' }, { country: "Costa d'Avorio", name: 'Inao Oulai' }, { country: "Costa d'Avorio", name: 'Sangaré' }, { country: "Costa d'Avorio", name: 'Seri' }, { country: "Costa d'Avorio", name: 'Adingra' }, { country: "Costa d'Avorio", name: 'Bonny' }, { country: "Costa d'Avorio", name: 'A. Diallo' }, { country: "Costa d'Avorio", name: 'Diakité' }, { country: "Costa d'Avorio", name: 'Y. Diomandé' }, { country: "Costa d'Avorio", name: 'Guessand' }, { country: "Costa d'Avorio", name: 'Pépé' }, { country: "Costa d'Avorio", name: 'Traoré' }, { country: "Costa d'Avorio", name: 'Wahi' },
    // --- GIAPPONE ---
    { country: 'Giappone', name: 'Nagatomo' }, { country: 'Giappone', name: 'Taniguchi' }, { country: 'Giappone', name: 'Itakura' }, { country: 'Giappone', name: 'Watanabe' }, { country: 'Giappone', name: 'Tomiyasu' }, { country: 'Giappone', name: 'Ito' }, { country: 'Giappone', name: 'Seko' }, { country: 'Giappone', name: 'Sugawara' }, { country: 'Giappone', name: 'Suzuki' }, { country: 'Giappone', name: 'Doan' }, { country: 'Giappone', name: 'Endo' }, { country: 'Giappone', name: 'Kamada' }, { country: 'Giappone', name: 'Kubo' }, { country: 'Giappone', name: 'Nakamura' }, { country: 'Giappone', name: 'Sano' }, { country: 'Giappone', name: 'Tanaka' }, { country: 'Giappone', name: 'Ogawa' }, { country: 'Giappone', name: 'Maeda' }, { country: 'Giappone', name: 'Ueda' }, { country: 'Giappone', name: 'Shiogai' }, { country: 'Giappone', name: 'Goto' },
    // --- OLANDA ---
    { country: 'Olanda', name: 'Akè' }, { country: 'Olanda', name: 'Van Dijk' }, { country: 'Olanda', name: 'Dumfries' }, { country: 'Olanda', name: 'Hato' }, { country: 'Olanda', name: 'Van Hecke' }, { country: 'Olanda', name: 'Van De Ven' }, { country: 'Olanda', name: 'J. Timber' }, { country: 'Olanda', name: 'De Jong' }, { country: 'Olanda', name: 'Gravenberch' }, { country: 'Olanda', name: 'Koopmeiners' }, { country: 'Olanda', name: 'Reijnders' }, { country: 'Olanda', name: 'De Roon' }, { country: 'Olanda', name: 'Til' }, { country: 'Olanda', name: 'Q. Timber' }, { country: 'Olanda', name: 'Wieffer' }, { country: 'Olanda', name: 'Brobbey' }, { country: 'Olanda', name: 'Depay' }, { country: 'Olanda', name: 'Gakpo' }, { country: 'Olanda', name: 'Kluivert' }, { country: 'Olanda', name: 'Lang' }, { country: 'Olanda', name: 'Malen' }, { country: 'Olanda', name: 'Summerville' }, { country: 'Olanda', name: 'Weghorst' },
    // --- SVEZIA ---
    { country: 'Svezia', name: 'Ekdal' }, { country: 'Svezia', name: 'Gudmundsson' }, { country: 'Svezia', name: 'Hien' }, { country: 'Svezia', name: 'Johansson' }, { country: 'Svezia', name: 'Lagerbielke' }, { country: 'Svezia', name: 'Lindelof' }, { country: 'Svezia', name: 'Smith' }, { country: 'Svezia', name: 'Starfelt' }, { country: 'Svezia', name: 'Stroud' }, { country: 'Svezia', name: 'Svensson' }, { country: 'Svezia', name: 'Ali' }, { country: 'Svezia', name: 'Ayari' }, { country: 'Svezia', name: 'Bergvall' }, { country: 'Svezia', name: 'Karlstrom' }, { country: 'Svezia', name: 'Sema' }, { country: 'Svezia', name: 'Svanberg' }, { country: 'Svezia', name: 'Zeneli' }, { country: 'Svezia', name: 'Bernhardsson' }, { country: 'Svezia', name: 'Elanga' }, { country: 'Svezia', name: 'Gyokeres' }, { country: 'Svezia', name: 'Isak' }, { country: 'Svezia', name: 'Nilsson' }, { country: 'Svezia', name: 'Nygren' },
    // --- TUNISIA ---
    { country: 'Tunisia', name: 'Talbi' }, { country: 'Tunisia', name: 'Bronn' }, { country: 'Tunisia', name: 'Rekik' }, { country: 'Tunisia', name: 'Valery' }, { country: 'Tunisia', name: 'Abdi' }, { country: 'Tunisia', name: 'Ben Hamida' }, { country: 'Tunisia', name: 'Arous' }, { country: 'Tunisia', name: 'Chikhaoui' }, { country: 'Tunisia', name: 'Neffati' }, { country: 'Tunisia', name: 'Skhiri' }, { country: 'Tunisia', name: 'Mejbri' }, { country: 'Tunisia', name: 'Ben Slimane' }, { country: 'Tunisia', name: 'Gharbi' }, { country: 'Tunisia', name: 'Hadj Mahmoud' }, { country: 'Tunisia', name: 'Khedira' }, { country: 'Tunisia', name: 'Ben Ouanes' }, { country: 'Tunisia', name: 'Achouri' }, { country: 'Tunisia', name: 'Ayari' }, { country: 'Tunisia', name: 'Chaouat' }, { country: 'Tunisia', name: 'Elloumi' }, { country: 'Tunisia', name: 'Mastouri' }, { country: 'Tunisia', name: 'Saad' }, { country: 'Tunisia', name: 'Tounekti' },
    // --- BELGIO ---
    { country: 'Belgio', name: 'Castagne' }, { country: 'Belgio', name: 'Debast' }, { country: 'Belgio', name: 'De Cuyper' }, { country: 'Belgio', name: 'De Winter' }, { country: 'Belgio', name: 'Mechele' }, { country: 'Belgio', name: 'Meunier' }, { country: 'Belgio', name: 'Ngoy' }, { country: 'Belgio', name: 'Seys' }, { country: 'Belgio', name: 'Theate' }, { country: 'Belgio', name: 'De Bruyne' }, { country: 'Belgio', name: 'Onana' }, { country: 'Belgio', name: 'Raskin' }, { country: 'Belgio', name: 'Tielemans' }, { country: 'Belgio', name: 'Vanaken' }, { country: 'Belgio', name: 'Witsel' }, { country: 'Belgio', name: 'De Ketelaere' }, { country: 'Belgio', name: 'Doku' }, { country: 'Belgio', name: 'Fernandez Pardo' }, { country: 'Belgio', name: 'Lukaku' }, { country: 'Belgio', name: 'Lukebakio' }, { country: 'Belgio', name: 'D. Moreira' }, { country: 'Belgio', name: 'Saelemaekers' }, { country: 'Belgio', name: 'Trossard' },
    // --- EGITTO ---
    { country: 'Egitto', name: 'Hany' }, { country: 'Egitto', name: 'Tarek Alaa' }, { country: 'Egitto', name: 'Fathi' }, { country: 'Egitto', name: 'Rabia' }, { country: 'Egitto', name: 'Yasser Ibrahim' }, { country: 'Egitto', name: 'Abdelmaguid' }, { country: 'Egitto', name: 'Abdelmonem' }, { country: 'Egitto', name: 'Fattouh' }, { country: 'Egitto', name: 'Hafez' }, { country: 'Egitto', name: 'Attia' }, { country: 'Egitto', name: 'Lasheen' }, { country: 'Egitto', name: 'Dunga' }, { country: 'Egitto', name: 'Saber' }, { country: 'Egitto', name: 'Zizo' }, { country: 'Egitto', name: 'Trezeguet' }, { country: 'Egitto', name: 'Ashour' }, { country: 'Egitto', name: 'Ziko' }, { country: 'Egitto', name: 'Adel' }, { country: 'Egitto', name: 'Hassan' }, { country: 'Egitto', name: 'Salah' }, { country: 'Egitto', name: 'Marmoush' }, { country: 'Egitto', name: 'Abdullah' }, { country: 'Egitto', name: 'Abdelkarim' },
    // --- IRAN ---
    { country: 'Iran', name: 'Eiri' }, { country: 'Iran', name: 'Hajsafi' }, { country: 'Iran', name: 'Hardani' }, { country: 'Iran', name: 'Kanaani' }, { country: 'Iran', name: 'Khalilzadeh' }, { country: 'Iran', name: 'Mohammadi' }, { country: 'Iran', name: 'Noorafkan' }, { country: 'Iran', name: 'Rezaeian' }, { country: 'Iran', name: 'Cheshmi' }, { country: 'Iran', name: 'Ezatolahi' }, { country: 'Iran', name: 'Ghaedi' }, { country: 'Iran', name: 'Ghoddos' }, { country: 'Iran', name: 'Ghorbani' }, { country: 'Iran', name: 'Jahanbakhsh' }, { country: 'Iran', name: 'Mohebi' }, { country: 'Iran', name: 'Razzaghinia' }, { country: 'Iran', name: 'Torabi' }, { country: 'Iran', name: 'Yousefi' }, { country: 'Iran', name: 'Alipour' }, { country: 'Iran', name: 'Dargahi' }, { country: 'Iran', name: 'Hosseinzadeh' }, { country: 'Iran', name: 'Moghanlou' }, { country: 'Iran', name: 'Taremi' },
    // --- NUOVA ZELANDA ---
    { country: 'Nuova Zelanda', name: 'Bindon' }, { country: 'Nuova Zelanda', name: 'Boxall' }, { country: 'Nuova Zelanda', name: 'Cacace' }, { country: 'Nuova Zelanda', name: 'De Vries' }, { country: 'Nuova Zelanda', name: 'Elliot' }, { country: 'Nuova Zelanda', name: 'Payne' }, { country: 'Nuova Zelanda', name: 'Pijnaker' }, { country: 'Nuova Zelanda', name: 'Smith' }, { country: 'Nuova Zelanda', name: 'Surman' }, { country: 'Nuova Zelanda', name: 'Bayliss' }, { country: 'Nuova Zelanda', name: 'Bell' }, { country: 'Nuova Zelanda', name: 'Rufer' }, { country: 'Nuova Zelanda', name: 'Stamenic' }, { country: 'Nuova Zelanda', name: 'Thomas' }, { country: 'Nuova Zelanda', name: 'Barbarouses' }, { country: 'Nuova Zelanda', name: 'Garbett' }, { country: 'Nuova Zelanda', name: 'Just' }, { country: 'Nuova Zelanda', name: 'McCowatt' }, { country: 'Nuova Zelanda', name: 'Old' }, { country: 'Nuova Zelanda', name: 'Randall' }, { country: 'Nuova Zelanda', name: 'Singh' }, { country: 'Nuova Zelanda', name: 'Waine' }, { country: 'Nuova Zelanda', name: 'Wood' },
    // --- CAPO VERDE ---
    { country: 'Capo Verde', name: 'Lopes Cabral' }, { country: 'Capo Verde', name: 'Diney Borges' }, { country: 'Capo Verde', name: 'Logan Costa' }, { country: 'Capo Verde', name: '⁠Roberto Lopes' }, { country: 'Capo Verde', name: 'Moreira' }, { country: 'Capo Verde', name: 'P. Pina' }, { country: 'Capo Verde', name: 'Pires' }, { country: 'Capo Verde', name: 'Stopira' }, { country: 'Capo Verde', name: 'Arcanjo' }, { country: 'Capo Verde', name: 'Duarte' }, { country: 'Capo Verde', name: 'Laros Duarte' }, { country: 'Capo Verde', name: 'Joao Paulo' }, { country: 'Capo Verde', name: 'Monteiro' }, { country: 'Capo Verde', name: 'C. Pina' }, { country: 'Capo Verde', name: 'S. Semedo' }, { country: 'Capo Verde', name: 'Benchimol' }, { country: 'Capo Verde', name: 'Cabral' }, { country: 'Capo Verde', name: 'Livramento' }, { country: 'Capo Verde', name: 'Mendes' }, { country: 'Capo Verde', name: 'Da Costa' }, { country: 'Capo Verde', name: 'Rodrigues' }, { country: 'Capo Verde', name: 'W. Semedo' }, { country: 'Capo Verde', name: 'Varela' },
    // --- ARABIA SAUDITA ---
    { country: 'Arabia Saudita', name: 'Al Amri' }, { country: 'Arabia Saudita', name: 'Tambakti' }, { country: 'Arabia Saudita', name: 'Thikri' }, { country: 'Arabia Saudita', name: 'Lajami' }, { country: 'Arabia Saudita', name: 'Kadesh' }, { country: 'Arabia Saudita', name: 'Abdulhamid' }, { country: 'Arabia Saudita', name: 'Al Shamat' }, { country: 'Arabia Saudita', name: 'Majrashi' }, { country: 'Arabia Saudita', name: 'Al Harbi' }, { country: 'Arabia Saudita', name: 'Boushal' }, { country: 'Arabia Saudita', name: 'Al-Ghannam' }, { country: 'Arabia Saudita', name: 'Kanno' }, { country: 'Arabia Saudita', name: 'Al Khaibari' }, { country: 'Arabia Saudita', name: 'Al Johani' }, { country: 'Arabia Saudita', name: 'N. Al Dawsari' }, { country: 'Arabia Saudita', name: 'Al Juwayr' }, { country: 'Arabia Saudita', name: 'Al Hajji' }, { country: 'Arabia Saudita', name: 'S. Al Dawsari' }, { country: 'Arabia Saudita', name: 'Al Ghannam' }, { country: 'Arabia Saudita', name: 'Yahya' }, { country: 'Arabia Saudita', name: 'Al Buraikan' }, { country: 'Arabia Saudita', name: 'Al Shehri' }, { country: 'Arabia Saudita', name: 'Al Hamdan' },
    // --- SPAGNA ---
    { country: 'Spagna', name: 'Llorente' }, { country: 'Spagna', name: 'Porro' }, { country: 'Spagna', name: 'Cubarsì' }, { country: 'Spagna', name: 'Pubill' }, { country: 'Spagna', name: 'Laporte' }, { country: 'Spagna', name: 'Eric Garcia' }, { country: 'Spagna', name: 'Cucurella' }, { country: 'Spagna', name: 'Grimaldo' }, { country: 'Spagna', name: 'Pedri' }, { country: 'Spagna', name: 'Rodri' }, { country: 'Spagna', name: 'Zubimendi' }, { country: 'Spagna', name: 'Fabian Ruiz' }, { country: 'Spagna', name: 'Gavi' }, { country: 'Spagna', name: 'Mikel Merino' }, { country: 'Spagna', name: 'Baena' }, { country: 'Spagna', name: 'Yamal' }, { country: 'Spagna', name: 'Yeremy Pino' }, { country: 'Spagna', name: 'Oyarzabal' }, { country: 'Spagna', name: 'Ferran' }, { country: 'Spagna', name: 'Borja Iglesias' }, { country: 'Spagna', name: 'Nico Williams' }, { country: 'Spagna', name: 'Victor Munoz' }, { country: 'Spagna', name: 'Olmo' },
    // --- URUGUAY ---
    { country: 'Uruguay', name: 'Varela' }, { country: 'Uruguay', name: 'R. Araujo' }, { country: 'Uruguay', name: 'José Gimenez' }, { country: 'Uruguay', name: 'Bueno' }, { country: 'Uruguay', name: 'Caceres' }, { country: 'Uruguay', name: 'Olivera' }, { country: 'Uruguay', name: 'Piquerez' }, { country: 'Uruguay', name: 'Vina' }, { country: 'Uruguay', name: 'Ugarte' }, { country: 'Uruguay', name: 'Martinez' }, { country: 'Uruguay', name: 'Bentancur' }, { country: 'Uruguay', name: 'Valverde' }, { country: 'Uruguay', name: 'Canobbio' }, { country: 'Uruguay', name: 'Sanabria' }, { country: 'Uruguay', name: 'De Arrascaeta' }, { country: 'Uruguay', name: 'De la Cruz' }, { country: 'Uruguay', name: 'Zalazar' }, { country: 'Uruguay', name: 'Pellistri' }, { country: 'Uruguay', name: 'M. Araujo' }, { country: 'Uruguay', name: 'Rodriguez' }, { country: 'Uruguay', name: 'Aguirre' }, { country: 'Uruguay', name: 'Vinas' }, { country: 'Uruguay', name: 'Nunez' },
    // --- FRANCIA ---
    { country: 'Francia', name: 'Digne' }, { country: 'Francia', name: 'Gusto' }, { country: 'Francia', name: 'Lucas Hernandez' }, { country: 'Francia', name: 'Theo Hernandez' }, { country: 'Francia', name: 'Konaté' }, { country: 'Francia', name: 'Koundé' }, { country: 'Francia', name: 'Lacroix' }, { country: 'Francia', name: 'Saliba' }, { country: 'Francia', name: 'Upamecano' }, { country: 'Francia', name: 'Kanté' }, { country: 'Francia', name: 'Koné' }, { country: 'Francia', name: 'Rabiot' }, { country: 'Francia', name: 'Tchouameni' }, { country: 'Francia', name: 'Zaïre-Emery' }, { country: 'Francia', name: 'Akliouche' }, { country: 'Francia', name: 'Barcola' }, { country: 'Francia', name: 'Cherki' }, { country: 'Francia', name: 'Dembélé' }, { country: 'Francia', name: 'Doué' }, { country: 'Francia', name: 'Mateta' }, { country: 'Francia', name: 'Mbappé' }, { country: 'Francia', name: 'Olise' }, { country: 'Francia', name: 'Thuram' },
    // --- IRAQ ---
    { country: 'Iraq', name: 'Ali' }, { country: 'Iraq', name: 'Younis' }, { country: 'Iraq', name: 'Yahya' }, { country: 'Iraq', name: 'Saadoon' }, { country: 'Iraq', name: 'Tahseen' }, { country: 'Iraq', name: 'Sulaka' }, { country: 'Iraq', name: 'Hashim' }, { country: 'Iraq', name: 'Doski' }, { country: 'Iraq', name: 'Ismail' }, { country: 'Iraq', name: 'Putros' }, { country: 'Iraq', name: 'Al-Ammari' }, { country: 'Iraq', name: 'Yakob' }, { country: 'Iraq', name: 'Iqbal' }, { country: 'Iraq', name: 'Sher' }, { country: 'Iraq', name: 'Bayesh' }, { country: 'Iraq', name: 'Qasem' }, { country: 'Iraq', name: 'Amyn' }, { country: 'Iraq', name: 'Farji' }, { country: 'Iraq', name: 'Jassim' }, { country: 'Iraq', name: 'Al-Hamadi' }, { country: 'Iraq', name: 'Yousef' }, { country: 'Iraq', name: 'Hussein' },
    // --- NORVEGIA ---
    { country: 'Norvegia', name: 'Vassbakk Ajer' }, { country: 'Norvegia', name: 'Bjorkan' }, { country: 'Norvegia', name: 'Falchener' }, { country: 'Norvegia', name: 'Langas' }, { country: 'Norvegia', name: 'Heggem' }, { country: 'Norvegia', name: 'Pedersen' }, { country: 'Norvegia', name: 'Ryerson' }, { country: 'Norvegia', name: 'Moller Wolfe' }, { country: 'Norvegia', name: 'Ostigard' }, { country: 'Norvegia', name: 'Aasgaard' }, { country: 'Norvegia', name: 'Aursnes' }, { country: 'Norvegia', name: 'Berg' }, { country: 'Norvegia', name: 'Berge' }, { country: 'Norvegia', name: 'Bobb' }, { country: 'Norvegia', name: 'Hauge' }, { country: 'Norvegia', name: 'Nusa' }, { country: 'Norvegia', name: 'Schjelderup' }, { country: 'Norvegia', name: 'Thorsby' }, { country: 'Norvegia', name: 'Thorstvedt' }, { country: 'Norvegia', name: 'Odegaard' }, { country: 'Norvegia', name: 'Haaland' }, { country: 'Norvegia', name: 'Strand Larsen' }, { country: 'Norvegia', name: 'Sorloth' },
    // --- SENEGAL ---
    { country: 'Senegal', name: 'Diatta' }, { country: 'Senegal', name: 'Antoine Mendy' }, { country: 'Senegal', name: 'Koulibaly' }, { country: 'Senegal', name: 'El Hadji Malick Diouf' }, { country: 'Senegal', name: 'Mamadou Sarr' }, { country: 'Senegal', name: 'Niakhaté' }, { country: 'Senegal', name: 'Mbow' }, { country: 'Senegal', name: 'Seck' }, { country: 'Senegal', name: 'Jakobs' }, { country: 'Senegal', name: 'Ilay Camara' }, { country: 'Senegal', name: 'Idrissa Gueye' }, { country: 'Senegal', name: 'Pape Gueye' }, { country: 'Senegal', name: 'Lamine Camara' }, { country: 'Senegal', name: 'Diarra' }, { country: 'Senegal', name: 'Ciss' }, { country: 'Senegal', name: 'Pape Matar Sarr' }, { country: 'Senegal', name: 'Sapoko Ndiaye' }, { country: 'Senegal', name: 'Mané' }, { country: 'Senegal', name: 'Ismaïla Sarr' }, { country: 'Senegal', name: 'Iliman Ndiaye' }, { country: 'Senegal', name: 'Diao' }, { country: 'Senegal', name: 'Mbaye' }, { country: 'Senegal', name: 'Jackson' }, { country: 'Senegal', name: 'Dieng' }, { country: 'Senegal', name: 'Cherif Ndiaye' },
    // --- ALGERIA ---
    { country: 'Algeria', name: 'Belghali' }, { country: 'Algeria', name: 'Abada' }, { country: 'Algeria', name: 'Ait-Nouri' }, { country: 'Algeria', name: 'Chergui' }, { country: 'Algeria', name: 'Hadjam' }, { country: 'Algeria', name: 'Belaid' }, { country: 'Algeria', name: 'Tougai' }, { country: 'Algeria', name: 'Bensebaïni' }, { country: 'Algeria', name: 'Mandi' }, { country: 'Algeria', name: 'Boudaoui' }, { country: 'Algeria', name: 'Aouar' }, { country: 'Algeria', name: 'Bentaleb' }, { country: 'Algeria', name: 'Zerrouki' }, { country: 'Algeria', name: 'Titraoui' }, { country: 'Algeria', name: 'Maza' }, { country: 'Algeria', name: 'Chaibi' }, { country: 'Algeria', name: 'Mahrez' }, { country: 'Algeria', name: 'Hadj-Moussa' }, { country: 'Algeria', name: 'Amoura' }, { country: 'Algeria', name: 'Benbouali' }, { country: 'Algeria', name: 'Boulbina' }, { country: 'Algeria', name: 'Gouiri' }, { country: 'Algeria', name: 'Ghedjemis' },
    // --- ARGENTINA ---
    { country: 'Argentina', name: 'Montiel' }, { country: 'Argentina', name: 'Molina' }, { country: 'Argentina', name: 'Lisandro Martinez' }, { country: 'Argentina', name: 'Otamendi' }, { country: 'Argentina', name: 'Balerdi' }, { country: 'Argentina', name: 'Romero' }, { country: 'Argentina', name: 'Tagliafico' }, { country: 'Argentina', name: 'Medina' }, { country: 'Argentina', name: 'Lo Celso' }, { country: 'Argentina', name: 'Paredes' }, { country: 'Argentina', name: 'De Paul' }, { country: 'Argentina', name: 'Palacios' }, { country: 'Argentina', name: 'Fernandez' }, { country: 'Argentina', name: 'Mac Allister' }, { country: 'Argentina', name: 'Barco' }, { country: 'Argentina', name: 'Messi' }, { country: 'Argentina', name: 'Gonzalez' }, { country: 'Argentina', name: 'Simeone' }, { country: 'Argentina', name: 'Lautaro Martinez' }, { country: 'Argentina', name: 'Lopez' }, { country: 'Argentina', name: 'Alvarez' }, { country: 'Argentina', name: 'Almada' }, { country: 'Argentina', name: 'Paz' },
    // --- AUSTRIA ---
    { country: 'Austria', name: 'Affengruber' }, { country: 'Austria', name: 'Alaba' }, { country: 'Austria', name: 'Danso' }, { country: 'Austria', name: 'Friedl' }, { country: 'Austria', name: 'Lienhart' }, { country: 'Austria', name: 'Mwene' }, { country: 'Austria', name: 'Posch' }, { country: 'Austria', name: 'Prass' }, { country: 'Austria', name: 'Svoboda' }, { country: 'Austria', name: 'Chukwuemeka' }, { country: 'Austria', name: 'Grillitsch' }, { country: 'Austria', name: 'Laimer' }, { country: 'Austria', name: 'Sabitzer' }, { country: 'Austria', name: 'Schlager' }, { country: 'Austria', name: 'Schmid' }, { country: 'Austria', name: 'Schopf' }, { country: 'Austria', name: 'Seiwald' }, { country: 'Austria', name: 'Wanner' }, { country: 'Austria', name: 'Wimmer' }, { country: 'Austria', name: 'Arnautovic' }, { country: 'Austria', name: 'Gregoritsch' }, { country: 'Austria', name: 'Kalajdzic' },
    // --- GIORDANIA ---
    { country: 'Giordania', name: 'Al-Arab' }, { country: 'Giordania', name: 'Nasib' }, { country: 'Giordania', name: 'Al-Rosan' }, { country: 'Giordania', name: 'Abu Dahba' }, { country: 'Giordania', name: 'Abualnadi' }, { country: 'Giordania', name: 'Obaid' }, { country: 'Giordania', name: 'Abu Hashees' }, { country: 'Giordania', name: 'Abu Taha' }, { country: 'Giordania', name: 'Haddad' }, { country: 'Giordania', name: 'Badawi' }, { country: 'Giordania', name: 'Al-Rahsdan' }, { country: 'Giordania', name: 'Jamous' }, { country: 'Giordania', name: 'Al-Rawabdeh' }, { country: 'Giordania', name: 'Saadeh' }, { country: 'Giordania', name: 'Ayed' }, { country: 'Giordania', name: 'Al-Dawoud' }, { country: 'Giordania', name: 'Al-Mardi' }, { country: 'Giordania', name: 'Fakhouri' }, { country: 'Giordania', name: 'Al-Tamari' }, { country: 'Giordania', name: 'Shararh' }, { country: 'Giordania', name: 'Azaizeh' }, { country: 'Giordania', name: 'Ali Olwan' }, { country: 'Giordania', name: 'Sabra' },
    // --- COLOMBIA ---
    { country: 'Colombia', name: 'Sanchez' }, { country: 'Colombia', name: 'Lucumí' }, { country: 'Colombia', name: 'Mina' }, { country: 'Colombia', name: 'Ditta' }, { country: 'Colombia', name: 'Munoz' }, { country: 'Colombia', name: 'Santiago Arias' }, { country: 'Colombia', name: 'Mojica' }, { country: 'Colombia', name: 'Machado' }, { country: 'Colombia', name: 'Rios' }, { country: 'Colombia', name: 'Lerma' }, { country: 'Colombia', name: 'Castano' }, { country: 'Colombia', name: 'Portilla' }, { country: 'Colombia', name: 'Puerta' }, { country: 'Colombia', name: 'Jhon Arias' }, { country: 'Colombia', name: 'Carrascal' }, { country: 'Colombia', name: 'Quintero' }, { country: 'Colombia', name: 'James Rodriguez' }, { country: 'Colombia', name: 'Campaz' }, { country: 'Colombia', name: 'Hernandez' }, { country: 'Colombia', name: 'Luis Diaz' }, { country: 'Colombia', name: 'Suarez' }, { country: 'Colombia', name: 'Gomez' }, { country: 'Colombia', name: 'Cordoba' },
    // --- R.D. CONGO ---
    { country: 'R.D. Congo', name: 'Wan-Bissaka' }, { country: 'R.D. Congo', name: 'Kalulu' }, { country: 'R.D. Congo', name: 'Kayembe' }, { country: 'R.D. Congo', name: 'Masuaku' }, { country: 'R.D. Congo', name: 'Kapuadi' }, { country: 'R.D. Congo', name: 'Tshibola' }, { country: 'R.D. Congo', name: 'Tuanzebe' }, { country: 'R.D. Congo', name: 'Mbemba' }, { country: 'R.D. Congo', name: 'Batubinsika' }, { country: 'R.D. Congo', name: 'Sadiki' }, { country: 'R.D. Congo', name: 'Moutoussamy' }, { country: 'R.D. Congo', name: 'E. Kayembe' }, { country: 'R.D. Congo', name: 'Mukau' }, { country: 'R.D. Congo', name: 'Pickel' }, { country: 'R.D. Congo', name: 'Mbuku' }, { country: 'R.D. Congo', name: 'Cipenga' }, { country: 'R.D. Congo', name: 'Elia' }, { country: 'R.D. Congo', name: 'Bongonda' }, { country: 'R.D. Congo', name: 'Kakuta' }, { country: 'R.D. Congo', name: 'Mayele' }, { country: 'R.D. Congo', name: 'Bakambu' }, { country: 'R.D. Congo', name: 'Banza' }, { country: 'R.D. Congo', name: 'Wissa' },
    // --- PORTOGALLO ---
    { country: 'Portogallo', name: 'Dalot' }, { country: 'Portogallo', name: 'Matheus Nunes' }, { country: 'Portogallo', name: 'Semedo' }, { country: 'Portogallo', name: 'Cancelo' }, { country: 'Portogallo', name: 'Nuno Mendes' }, { country: 'Portogallo', name: 'Gonçalo Inacio' }, { country: 'Portogallo', name: 'Veiga' }, { country: 'Portogallo', name: 'Ruben Dias' }, { country: 'Portogallo', name: 'Araujo' }, { country: 'Portogallo', name: 'Ruben Neves' }, { country: 'Portogallo', name: 'Samu Costa' }, { country: 'Portogallo', name: 'Joao Neves' }, { country: 'Portogallo', name: 'Vitinha' }, { country: 'Portogallo', name: 'Bruno Fernandes' }, { country: 'Portogallo', name: 'Bernardo Silva' }, { country: 'Portogallo', name: 'Joao Felix' }, { country: 'Portogallo', name: 'Trinçao' }, { country: 'Portogallo', name: 'Conceiçao' }, { country: 'Portogallo', name: 'Pedro Neto' }, { country: 'Portogallo', name: 'Leao' }, { country: 'Portogallo', name: 'Guedes' }, { country: 'Portogallo', name: 'Ramos' }, { country: 'Portogallo', name: 'Cristiano Ronaldo' },
    // --- UZBEKISTAN ---
    { country: 'Uzbekistan', name: 'O‘lmasaliyev' }, { country: 'Uzbekistan', name: 'O‘rozov' }, { country: 'Uzbekistan', name: 'Ashurmatov' }, { country: 'Uzbekistan', name: 'Eshmurodov' }, { country: 'Uzbekistan', name: 'Khusanov' }, { country: 'Uzbekistan', name: 'Abdullayev' }, { country: 'Uzbekistan', name: 'Sayfiyev' }, { country: 'Uzbekistan', name: 'Alijonov' }, { country: 'Uzbekistan', name: 'Nasrullayev' }, { country: 'Uzbekistan', name: 'Karimov' }, { country: 'Uzbekistan', name: 'Esanov' }, { country: 'Uzbekistan', name: 'Hamrobekov' }, { country: 'Uzbekistan', name: 'Mozgovoy' }, { country: 'Uzbekistan', name: 'Shukurov' }, { country: 'Uzbekistan', name: 'Iskanderov' }, { country: 'Uzbekistan', name: 'Ganiev' }, { country: 'Uzbekistan', name: 'Fayzullayev' }, { country: 'Uzbekistan', name: 'Masharipov' }, { country: 'Uzbekistan', name: 'Hamdamov' }, { country: 'Uzbekistan', name: 'Urunov' }, { country: 'Uzbekistan', name: 'Amonov' }, { country: 'Uzbekistan', name: 'Sergeyev' }, { country: 'Uzbekistan', name: 'Shomurodov' },
    // --- CROAZIA ---
    { country: 'Croazia', name: 'Gvardiol' }, { country: 'Croazia', name: 'Caleta-Car' }, { country: 'Croazia', name: 'Sutalo' }, { country: 'Croazia', name: 'Stanisic' }, { country: 'Croazia', name: 'Pongracic' }, { country: 'Croazia', name: 'Erlic' }, { country: 'Croazia', name: 'Vuskovic' }, { country: 'Croazia', name: 'Modric' }, { country: 'Croazia', name: 'Mateo Kovacic' }, { country: 'Croazia', name: 'Mario Pasalic' }, { country: 'Croazia', name: 'Vlasic' }, { country: 'Croazia', name: 'Luka Sucic' }, { country: 'Croazia', name: 'Baturina' }, { country: 'Croazia', name: 'Jakic' }, { country: 'Croazia', name: 'Petar Sucic' }, { country: 'Croazia', name: 'Moro' }, { country: 'Croazia', name: 'Fruk' }, { country: 'Croazia', name: 'Perisic' }, { country: 'Croazia', name: 'Kramaric' }, { country: 'Croazia', name: 'Budimir' }, { country: 'Croazia', name: 'Marco Pasalic' }, { country: 'Croazia', name: 'Musa' }, { country: 'Croazia', name: 'Matanovic' },
    // --- INGHILTERRA ---
    { country: 'Inghilterra', name: 'James' }, { country: 'Inghilterra', name: 'Konsa' }, { country: 'Inghilterra', name: 'Quansah' }, { country: 'Inghilterra', name: 'Stones' }, { country: 'Inghilterra', name: 'Guehi' }, { country: 'Inghilterra', name: 'Burn' }, { country: 'Inghilterra', name: "O'Reilly" }, { country: 'Inghilterra', name: 'Spence' }, { country: 'Inghilterra', name: 'Livramento' }, { country: 'Inghilterra', name: 'Rice' }, { country: 'Inghilterra', name: 'Anderson' }, { country: 'Inghilterra', name: 'Mainoo' }, { country: 'Inghilterra', name: 'Jordan Henderson' }, { country: 'Inghilterra', name: 'Rogers' }, { country: 'Inghilterra', name: 'Bellingham' }, { country: 'Inghilterra', name: 'Eze' }, { country: 'Inghilterra', name: 'Kane' }, { country: 'Inghilterra', name: 'Toney' }, { country: 'Inghilterra', name: 'Watkins' }, { country: 'Inghilterra', name: 'Saka' }, { country: 'Inghilterra', name: 'Rashford' }, { country: 'Inghilterra', name: 'Gordon' }, { country: 'Inghilterra', name: 'Madueke' },
    // --- GHANA ---
    { country: 'Ghana', name: 'Rahman' }, { country: 'Ghana', name: 'Mensah' }, { country: 'Ghana', name: 'Senaya' }, { country: 'Ghana', name: 'Seidu' }, { country: 'Ghana', name: 'Mumin' }, { country: 'Ghana', name: 'Opoku' }, { country: 'Ghana', name: 'Adjetey' }, { country: 'Ghana', name: 'Peprah Oppong' }, { country: 'Ghana', name: 'Luckassen' }, { country: 'Ghana', name: 'Owusu' }, { country: 'Ghana', name: 'Partey' }, { country: 'Ghana', name: 'Sibo' }, { country: 'Ghana', name: 'Boakye' }, { country: 'Ghana', name: 'Yirenkyi' }, { country: 'Ghana', name: 'Fatawu Issahaku' }, { country: 'Ghana', name: 'Sulemana' }, { country: 'Ghana', name: 'Bonsu Baah' }, { country: 'Ghana', name: 'Nuamah' }, { country: 'Ghana', name: 'Semenyo' }, { country: 'Ghana', name: 'Thomas-Asante' }, { country: 'Ghana', name: 'Adu' }, { country: 'Ghana', name: 'Inaki Williams' }, { country: 'Ghana', name: 'Ayew' },
    // --- PANAMA ---
    { country: 'Panama', name: 'Blackman' }, { country: 'Panama', name: 'Gutierrez' }, { country: 'Panama', name: 'Murillo' }, { country: 'Panama', name: 'Escobar' }, { country: 'Panama', name: 'Andrade' }, { country: 'Panama', name: 'Fariaa' }, { country: 'Panama', name: 'Cordoba' }, { country: 'Panama', name: 'Davis' }, { country: 'Panama', name: 'Ramos' }, { country: 'Panama', name: 'Miller' }, { country: 'Panama', name: 'Godoy' }, { country: 'Panama', name: 'Carrasquilla' }, { country: 'Panama', name: 'Harvey' }, { country: 'Panama', name: 'Martinez' }, { country: 'Panama', name: 'Rodríguez' }, { country: 'Panama', name: 'Yanis' }, { country: 'Panama', name: 'Barcenas' }, { country: 'Panama', name: 'Quintero' }, { country: 'Panama', name: 'Londono' }, { country: 'Panama', name: 'Diaz' }, { country: 'Panama', name: 'Waterman' }, { country: 'Panama', name: 'Fajardo' }, { country: 'Panama', name: 'Rodriguez' }
  ].sort((a, b) => a.country.localeCompare(b.country) || a.name.localeCompare(b.name));
  
  export const WORLD_CUP_GOALKEEPERS = [
    // --- REP. CECA ---
    { country: 'Rep. Ceca', name: 'Hornicek' }, { country: 'Rep. Ceca', name: 'Kovar' }, { country: 'Rep. Ceca', name: 'Stanek' },
    // --- MESSICO ---
    { country: 'Messico', name: 'Rangel' }, { country: 'Messico', name: 'Achevedo' }, { country: 'Messico', name: 'Ochoa' },
    // --- SUDAFRICA ---
    { country: 'Sudafrica', name: 'Williams' }, { country: 'Sudafrica', name: 'Goss' }, { country: 'Sudafrica', name: 'Chaine' },
    // --- COREA SUD ---
    { country: 'Corea Sud', name: 'Kim Seung-gyu' }, { country: 'Corea Sud', name: 'Song Bum-keun' }, { country: 'Corea Sud', name: 'Jo Hyeon-woo' },
    // --- BOSNIA ---
    { country: 'Bosnia', name: 'Vasilj' }, { country: 'Bosnia', name: 'Zlomislic' }, { country: 'Bosnia', name: 'Jurkas' },
    // --- CANADA ---
    { country: 'Canada', name: 'Crepeau' }, { country: 'Canada', name: 'St. Clair' }, { country: 'Canada', name: 'Goodman' },
    // --- QATAR ---
    { country: 'Qatar', name: 'Abunada' }, { country: 'Qatar', name: 'Barsham' }, { country: 'Qatar', name: 'Zakaria' },
    // --- SVIZZERA ---
    { country: 'Svizzera', name: 'Kobel' }, { country: 'Svizzera', name: 'Keller' }, { country: 'Svizzera', name: 'Mvogo' },
    // --- BRASILE ---
    { country: 'Brasile', name: 'Alisson' }, { country: 'Brasile', name: 'Ederson' }, { country: 'Brasile', name: 'Weverton' },
    // --- HAITI ---
    { country: 'Haiti', name: 'Placide' }, { country: 'Haiti', name: 'A. Pierre' }, { country: 'Haiti', name: 'Duverger' },
    // --- MAROCCO ---
    { country: 'Marocco', name: 'Bonou' }, { country: 'Marocco', name: 'El Kajoui' }, { country: 'Marocco', name: 'Tagnaouti' },
    // --- SCOZIA ---
    { country: 'Scozia', name: 'Gordon' }, { country: 'Scozia', name: 'Gunn' }, { country: 'Scozia', name: 'Kelly' },
    // --- AUSTRALIA ---
    { country: 'Australia', name: 'Beach' }, { country: 'Australia', name: 'Izzo' }, { country: 'Australia', name: 'Ryan' },
    // --- PARAGUAY ---
    { country: 'Paraguay', name: 'R. Fernandez' }, { country: 'Paraguay', name: 'Gill' }, { country: 'Paraguay', name: 'G. Olveira' },
    // --- TURCHIA ---
    { country: 'Turchia', name: 'Bayindir' }, { country: 'Turchia', name: 'Gunok' }, { country: 'Turchia', name: 'Cakir' },
    // --- USA ---
    { country: 'USA', name: 'Turner' }, { country: 'USA', name: 'Freese' }, { country: 'USA', name: 'Brady' },
    // --- CURAÇAO ---
    { country: 'Curaçao', name: 'Bodak' }, { country: 'Curaçao', name: 'Doornbusch' }, { country: 'Curaçao', name: 'Room' },
    // --- ECUADOR ---
    { country: 'Ecuador', name: 'Valle' }, { country: 'Ecuador', name: 'Ramirez' }, { country: 'Ecuador', name: 'Galindez' },
    // --- GERMANIA ---
    { country: 'Germania', name: 'Neuer' }, { country: 'Germania', name: 'Baumann' }, { country: 'Germania', name: 'Nubel' },
    // --- COSTA D'AVORIO ---
    { country: "Costa d'Avorio", name: 'Y. Fofana' }, { country: "Costa d'Avorio", name: 'Koné' }, { country: "Costa d'Avorio", name: 'Lafont' },
    // --- GIAPPONE ---
    { country: 'Giappone', name: 'Hayakawa' }, { country: 'Giappone', name: 'Osako' }, { country: 'Giappone', name: 'Suzuki' },
    // --- OLANDA ---
    { country: 'Olanda', name: 'Flekken' }, { country: 'Olanda', name: 'Roefs' }, { country: 'Olanda', name: 'Verbruggen' },
    // --- SVEZIA ---
    { country: 'Svezia', name: 'Johansson' }, { country: 'Svezia', name: 'Nordfeldt' }, { country: 'Svezia', name: 'Widell Zetterstrom' },
    // --- TUNISIA ---
    { country: 'Tunisia', name: 'Dahmen' }, { country: 'Tunisia', name: 'Ben Hassine' }, { country: 'Tunisia', name: 'Chamakh' },
    // --- BELGIO ---
    { country: 'Belgio', name: 'Courtois' }, { country: 'Belgio', name: 'Lammens' }, { country: 'Belgio', name: 'Penders' },
    // --- EGITTO ---
    { country: 'Egitto', name: 'El Shennawy' }, { country: 'Egitto', name: 'Shobeir' }, { country: 'Egitto', name: 'Soliman' }, { country: 'Egitto', name: 'Mohamed Alaa' },
    // --- IRAN ---
    { country: 'Iran', name: 'Beiranvand' }, { country: 'Iran', name: 'Hosseini' }, { country: 'Iran', name: 'Niazmand' },
    // --- NUOVA ZELANDA ---
    { country: 'Nuova Zelanda', name: 'Crocombe' }, { country: 'Nuova Zelanda', name: 'Paulsen' }, { country: 'Nuova Zelanda', name: 'Woud' },
    // --- CAPO VERDE ---
    { country: 'Capo Verde', name: 'Dos Santos' }, { country: 'Capo Verde', name: 'Rosa' }, { country: 'Capo Verde', name: 'Vozinha' },
    // --- ARABIA SAUDITA ---
    { country: 'Arabia Saudita', name: 'Al Owais' }, { country: 'Arabia Saudita', name: 'Al Aqidi' }, { country: 'Arabia Saudita', name: 'Al Kassar' },
    // --- SPAGNA ---
    { country: 'Spagna', name: 'Unai Simon' }, { country: 'Spagna', name: 'Raya' }, { country: 'Spagna', name: 'Joan Garcia' },
    // --- URUGUAY ---
    { country: 'Uruguay', name: 'Rochet' }, { country: 'Uruguay', name: 'Muslera' }, { country: 'Uruguay', name: 'Mele' },
    // --- FRANCIA ---
    { country: 'Francia', name: 'Maignan' }, { country: 'Francia', name: 'Risser' }, { country: 'Francia', name: 'Samba' },
    // --- IRAQ ---
    { country: 'Iraq', name: 'Talib' }, { country: 'Iraq', name: 'Hassan' }, { country: 'Iraq', name: 'Basil' },
    // --- NORVEGIA ---
    { country: 'Norvegia', name: 'Nyland' }, { country: 'Norvegia', name: 'Selvik' }, { country: 'Norvegia', name: 'Tangvik' },
    // --- SENEGAL ---
    { country: 'Senegal', name: 'Edouard Mendy' }, { country: 'Senegal', name: 'Diaw' }, { country: 'Senegal', name: 'Yehvann Diouf' },
    // --- ALGERIA ---
    { country: 'Algeria', name: 'Zidane' }, { country: 'Algeria', name: 'Benbot' }, { country: 'Algeria', name: 'Mastil' }, { country: 'Algeria', name: 'Ramdane' },
    // --- ARGENTINA ---
    { country: 'Argentina', name: 'Emiliano Martinez' }, { country: 'Argentina', name: 'Rulli' }, { country: 'Argentina', name: 'Musso' },
    // --- AUSTRIA ---
    { country: 'Austria', name: 'Pentz' }, { country: 'Austria', name: 'Schlager' }, { country: 'Austria', name: 'Wiegele' },
    // --- GIORDANIA ---
    { country: 'Giordania', name: 'Abulaila' }, { country: 'Giordania', name: 'Bani Attiah' }, { country: 'Giordania', name: 'Al-Fakhouri' },
    // --- COLOMBIA ---
    { country: 'Colombia', name: 'Vargas' }, { country: 'Colombia', name: 'Montero' }, { country: 'Colombia', name: 'Ospina' },
    // --- R.D. CONGO ---
    { country: 'R.D. Congo', name: 'Fayulu' }, { country: 'R.D. Congo', name: 'Mpasi' }, { country: 'R.D. Congo', name: 'Epolo' },
    // --- PORTOGALLO ---
    { country: 'Portogallo', name: 'Diogo Costa' }, { country: 'Portogallo', name: 'Sá' }, { country: 'Portogallo', name: 'Rui Silva' }, { country: 'Portogallo', name: 'Velho' },
    // --- UZBEKISTAN ---
    { country: 'Uzbekistan', name: 'Yusupov' }, { country: 'Uzbekistan', name: 'Ergashev' }, { country: 'Uzbekistan', name: 'Nematov' },
    // --- CROAZIA ---
    { country: 'Croazia', name: 'Livakovic' }, { country: 'Croazia', name: 'Kotarski' }, { country: 'Croazia', name: 'Pandur' },
    // --- INGHILTERRA ---
    { country: 'Inghilterra', name: 'Pickford' }, { country: 'Inghilterra', name: 'Dean Henderson' }, { country: 'Inghilterra', name: 'Trafford' },
    // --- GHANA ---
    { country: 'Ghana', name: 'Asare' }, { country: 'Ghana', name: 'Ati-Zigi' }, { country: 'Ghana', name: 'Anang' }, { country: 'Ghana', name: 'Agbasi' }, { country: 'Ghana', name: 'Reverson' },
    // --- PANAMA ---
    { country: 'Panama', name: 'Mosquera' }, { country: 'Panama', name: 'Mejia' }, { country: 'Panama', name: 'Samudio' }
  ].sort((a, b) => a.country.localeCompare(b.country) || a.name.localeCompare(b.name));